---
- name: Include tasks for Debian
  include: Debian.yml
  when: (ansible_distribution == "Debian") and
        (ansible_distribution_major_version|int >= 8 or ansible_lsb.codename == "stretch")

- name: Include tasks for RedHat
  include: RedHat.yml
  when: (ansible_os_family == "RedHat") and
        (ansible_distribution_major_version|int >= 7)

- name: Include tasks for Ubuntu
  include: Ubuntu.yml
  when: (ansible_distribution == "Ubuntu") and
        (ansible_distribution_version|int >= 14.04)
